### ISSUE TITLE
Stepwise reduction in CV in observer programme

### ISSUE THREAD

**Issue by tomlclegg** [tomlclegg/scoti#5]
Simulations of observer programme produce stepwise reductions in CV for all rejection rates.
Huge drop in refusal_rate=0.9 is especially unexplainable.
[link to plot in repo here](https://github.com/tomlclegg/scoti/blob/a3e0b403b9344f5e1c26f21bcb7b315453560cc3/output/refusal_obsprogramme_cv_vs_BPUE.png)

**Comment by tomlclegg** [comment]
Vessel effect not the issue. No change in bug when turned off.

**Comment by MargaretSiple-NOAA** [comment]
It also persists when you set a different seed. I thought maybe this was some kind of artifact of the random numbers but it is not; here's the same plot with a different seed:
 
![image](https://github.com/tomlclegg/scoti/assets/73858992/01937e63-5163-454a-9487-fbb7cd6a1088)

@dlusseau do you have any insights on this/ have you seen the same thing in any of your simulations?

**Comment by tomlclegg** [comment]
After yesterday's discussion and playing with the code, I've concluded the step-wise behavior is likely due to large refusal rate suppressing the realized vessel sampling, which is masked when plotting target proportion.

Large refusal rates mean that even though target proportion increases, the realised proportion doesn't change. Therefore, CV stays constant until the target proportion overcomes the refusal rate enough to add one more vessel. At refusal=0.9, that effect is so strong we only see it once and it's big because adding one more vessel to a small sample size has a huge effect.

As @dlusseau suggested yesterday, the small size of the fishery (n_boats = 31) doesn't help because it magnifies this effect, that would otherwise be squished if more boats made the x-axis longer.

Amended the "Note about simulation behavior" section of the markdown to explain this (commit: d112b1723132ba8b059691b87f92f3092f1caf9e).
